### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by Dentonknifeworks** [elafargue/rpi-tig#4]
I have installed this on a Pi 3 with 0 issue.
I then installed it on a pi for and I get a Bad Gateway when testing the database and dont get any data.
Any ideas?
Thanks

**Comment by ZL1LAC** [comment]
@Dentonknifeworks did you end up figuring this out?

**Comment by Dentonknifeworks** [comment]
Nope I did not

**Comment by ZL1LAC** [comment]
I had the same issue and I had to search for ages back found it.

It's to do with the updated version of Influxdb.  The script is calling for latest witch 2.0 has issues, you need to use the version before it.

Navigate to docker-compose.yml and change `image: influxdb:latest` to `image: influxdb:1.8.4-alpine` save and run the install again.

This should fix your bad gateway issue

**Comment by ZL1LAC** [comment]
@Dentonknifeworks

**Comment by elafargue** [comment]
Don't hesitate to send pull requests for fixes!

**Comment by elafargue** [comment]
Updated the repository, thanks for the feedback
