### ISSUE TITLE
InfluxDB dependency seems to be failing

### ISSUE THREAD

**Issue by ab0oo** [elafargue/rpi-tig#5]
Doing an initial install on my RPi4 running my goesproc system, and seeing this:

pi@wxrx:~/src/rpi-tig $ ./start.sh 
Changing ownership of grafana files to what the Docker image expects
Starting TIG stack in the background
Pulling influxdb (influxdb:1.8.4-alpine)...
1.8.4-alpine: Pulling from library/influxdb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
Waiting for InfluxDB to come up...Error: No such container: influxdb
.Error: No such container: influxdb
.Error: No such container: influxdb
....

Not sure what happened (Docker is not my strong suit), but it looks like something changed with influxdb's image that doesn't sit well with the Raspi architecture.
And thoughts on a solution?

-John

**Comment by joshspicer** [comment]
Looks like the alpine build of influxdb has not been compiled for your pi's architecture.  Omitting the `-alpine` to make the image `influxdb:1.8.4` seems to work.

**Comment by elafargue** [comment]
Updated `docker-compose.yml` with proper image definitions. Can you confirm whether this fixes the issues you are seeing?

**Comment by ZL1LAC** [comment]
I always thought docker was smart and would always select the right architecture for the tag you are using for example influxdb:lastest.

Very annoying and extra work to make sure its all working.

**Comment by ab0oo** [comment]
> Updated `docker-compose.yml` with proper image definitions. Can you confirm whether this fixes the issues you are seeing?

Can confirm, it's currently pulling the correct influxdb image.  Appreciate the work.
